package com.javaassistant.testsupport;

public enum StubMode {
    NON_TOOLING,
    CORRELATION_TOOL_RETRIEVAL,
    GC_COMPARE_TOOL_RETRIEVAL,
    GC_TOOL_RETRIEVAL,
    LEGACY_GC_TOOL_RETRIEVAL,
    GC_WINDOW_STREAK_TOOL_RETRIEVAL,
    LEGACY_GC_WINDOW_STREAK_TOOL_RETRIEVAL,
    JFR_TOOL_RETRIEVAL,
    SCENARIO_LAB_ROUTING
}
